_extends: .github
# https://github.com/apps/settings
# https://github.com/repository-settings/app

repository:
  #name: NewRepo
  description: Dockerised Rick Roll
  homepage: https://hub.docker.com/r/modem7/docker-rickroll
  topics: linux, docker, nginx, video, docker-container, docker-image, meme, prank, self-hosted, homelab, rickroll

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  has_projects: false
  has_discussions: false

  default_branch: master

  allow_squash_merge: true
  allow_rebase_merge: true
  allow_merge_commit: true

  # Auto-delete head branches after merge
  delete_branch_on_merge: true

  # Always suggest updating PR branches that are behind base
  allow_update_branch: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
