# syntax = docker/dockerfile:latest

FROM nginxinc/nginx-unprivileged:1.23.1-alpine

USER root

ARG UID=101
ARG GID=101

# Copy files into image
COPY --link onclick/download.jpg /usr/share/nginx/html/
COPY --link MP4/SD/rickroll.mp4 /usr/share/nginx/html/rickroll.mp4
COPY --link --chmod=755 80-generate-onlick.sh /docker-entrypoint.d

# Change permissions to index.html
RUN chown $UID:0 /usr/share/nginx/html/index.html

# Document what port is required
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=10s --retries=3 --start-period=10s \
    CMD curl -fSs 127.0.0.1:8080/healthz || exit 1

STOPSIGNAL SIGQUIT

USER $UID

CMD ["nginx", "-g", "daemon off;"]