name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
        - name: 'Auto-assign issue'
          uses: pozil/auto-assign-issue@v1.7.1
          with:
            assignees: modem7