name: Docker CI - 1080onclick

on:
  push:
    paths:
      - 1080/onclick/Dockerfile
  pull_request:
    paths:
      - 1080/onclick/Dockerfile
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 1080/onclick/Dockerfile
          pull: false
          push: false