name: Docker CI - youtube

on:
  push:
    paths:
      - base-fullbuild/Dockerfile
  pull_request:
    paths:
      - base-fullbuild/Dockerfile
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: youtube/Dockerfile
          pull: false
          push: false