name: Label Manager

on:
  push:
    paths:
      - '.github/config/labels.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Synchronize labels
        uses: julb/action-manage-label@v1
        with:
          from: .github/config/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}